import "src/styles/globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col justify-between item-center">
        <header className="h-12 w-full flex justify-center bg-indigo-500">header</header>
        <main className="flex-auto flex justify-center items-center bg-gray-900">{children}</main>
        <footer className="flex justify-center bg-indigo-400">footer</footer>
      </body>
    </html>
  );
}
