import Head from "next/head";
import Link from "next/link";
import { useCallback, useState } from "react";
import { api } from "src/utils/api";

export default function Home(): JSX.Element {
  const [word, setWord] = useState<string>("");
  const hello = api.word.hello.useQuery({ text: "from tRPC" });
  const data = api.challenge.getAll.useQuery();

  console.debug(data.data, "data");

  const { mutate } = api.challenge.create.useMutation();

  const handleClick = useCallback(() => {
    mutate({ text: word });
  }, [mutate, word]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="spell"
            >
              <h3 className="text-2xl font-bold">Spell</h3>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="course"
            >
              <h3 className="text-2xl font-bold">Course</h3>
            </Link>
          </div>
          <p className="text-2xl text-white">
            {hello.data ? hello.data.greeting : "Loading tRPC query..."}
          </p>
          <input onChange={(e) => { setWord(e.target.value); }} value={word} />
          <button onClick={handleClick} type="button">提交</button>
        </div>
      </main>
    </>
  );
}
